### ISSUE TITLE
link too much content to the web

### ISSUE THREAD

**Issue by orenfromberg** [orenfromberg/sefaria-reddit-torahbot#1]
https://www.reddit.com/r/Judaism/comments/zckg3g/comment/iyxijaz/?utm_source=reddit&utm_medium=web2x&context=3

**Comment by ummmbacon** [comment]
@orenfromberg looks like you took care of this in the response when you just send the link back if it is over 2000? 

```

if(len(text) > 2000):
...
```

**Comment by ummmbacon** [comment]
That also clears out the todo in that file?

**Comment by orenfromberg** [comment]
Yeah this can be closed. This issue was intended to handle the case when a reference returns too much text. Currently it will link all comments now with a link to Sefaria, but only render the text inline when it is under 2000 chars total.
